### ISSUE TITLE
Question (Not an issue)

### ISSUE THREAD

**Issue by James-von-Detroit** [frankmorgner/OpenSCToken#11]
Just thinking about how this basically converts TokenD to CTK. Would it be possible to do the opposite of that? Example, with cards that are like Card OS 5.3 and have been focused on CTK support and development, but programs still have a lot of TokenD support like Outlook 2019. Would it be possible to convert CTK to TokenD as another middleware layer and expanding PKI future tech into legacy type applications? I could see a big use for this.

**Comment by frankmorgner** [comment]
Sure, that's possible. However, I think that TokenD is a dead end. It's poorely documented and deprecated since years. After [making it hard for developers to create a TokenD service](https://github.com/OpenSC/OpenSC.tokend/issues/33), Apple will soon turn to users making it hard to use the TokenD interface...
